name: update patch
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dart Version Manager
        run: pip install dart_version_manager
      - name: Update Patch
        run: |
          dvm build up --no-verbose
          echo "PUBSPEC_VERSION=$(dvm patch up --no-verbose --keep-build)" >> $GITHUB_ENV
          echo "TAG_NAME=v$(dvm major get --no-verbose).$(dvm minor get --no-verbose).$(dvm patch get --no-verbose)" >> $GITHUB_ENV
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          add: pubspec.yaml
          message: 'chore: update version to ${{env.PUBSPEC_VERSION}}'
          tag: '${{env.TAG_NAME}}'
          default_author: github_actions
      - name: Update develop
        run: |
          git checkout develop
          git merge --ff-only main
      - name: Push develop
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: develop
